### Introduction to Data Science Course by University of Michigan
# Week1

#### FUNCTIONS

add_numbers is a function that takes two numbers and adds them together.

In [2]:
def add_numbers(x,y):
    return x+y

add_numbers(1,2)

3

add_numbers updated to take an optional 3rd parameter. Using print allows printing of multiple expressions within a single cell.

In [40]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z
    
print(add_numbers(1,2))
print(add_numbers(1,2,3))

3
6


add_numbers updated to take an optional flag parameter.

In [41]:
def add_numbers(x,y,z=None, flag=False):
    if(flag):
        print('Flag is true!')
    if (z==None):
        return x+y
    else:
        return x+y+z
    
print(add_numbers(1,2, flag=True))

Flag is true!
3


Assign function add_numbers to variable a.

In [16]:
def add_numbers(x,y):
    return x+y

a=add_numbers
a(1,2)

3

#### Types and Sequences

Use type to return the object's type.

In [17]:
type('This is a string')

str

In [21]:
type(None)

NoneType

In [23]:
type(1)

int

In [26]:
type(1.0)

float

In [28]:
type(add_numbers)

function

Tuples are an immutable (=tetap) data structure (cannot be altered).

In [29]:
x=(1, 'a', 2, 'b')
type(x)

tuple

Lists are a mutable data structure.

In [30]:
x=[1, 'a', 2, 'b']
type(x)

list

Use 'append' to append (=menambahkan) an object to a list.

In [45]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3, 3.3]


This is an example of how to loop through each item in the list.

In [32]:
for item in x:
    print(item)

1
a
2
b
3.3


Or using the indexing operator:

In [37]:
i=0
while(i!=len(x)):
    print(x[i])
    i=i+1

1
a
2
b
3.3


Use + to concatenate (=menggabungkan) lists.

In [42]:
[1,2]+[3,4]

[1, 2, 3, 4]

Use * to repeat lists.

In [43]:
[1]*3

[1, 1, 1]

In [44]:
[1,2,3]*2

[1, 2, 3, 1, 2, 3]

Use the 'in' operator to check if something is inside a list.

In [47]:
1 in x
# x is a list consists of [1, 'a', 2, 'b', 3.3]

True

In [48]:
3 in x

False

Use bracket notation to slice a string.

In [78]:
x = '1234567890ABCDEFGHIJ'
print(x[0]) 
print(x[1])
print(x[0:1])
print(x[0:10]) 

print(x[-1])
print(x[-11:-9])
print(x[9:11])

print(x[:10])
print(x[10:])

1
2
1
1234567890
J
0A
0A
1234567890
ABCDEFGHIJ


In [86]:
name = 'Melia Putri Handayani'
origin = 'Indonesia'

print(name + ' from ' + origin)
print(name*3)
print('lia Pu' in name) #to create search function

Melia Putri Handayani from Indonesia
Melia Putri HandayaniMelia Putri HandayaniMelia Putri Handayani
True


'split' returns a list of all the words in a string, or a list split on a specific character.

In [118]:
firstname1 = 'Melia Putri Handayani'.split(' ')[0]
print(firstname1)

firstname2 = 'Melia Putri Handayani'.split(' ')[0:1]
print(firstname2)

firstname3 = 'Melia Putri Handayani'.split(' ')[:1]
print(firstname3)

middlename = 'Melia Putri Handayani'.split(' ')[1:2]
print(middlename)

lastname1 = 'Melia Putri Handayani'.split(' ')[-1]
print(lastname1)

lastname2 = 'Melia Putri Handayani'.split(' ')[-1:]
print(lastname2)

Melia
['Melia']
['Melia']
['Putri']
Handayani
['Handayani']


In [125]:
aa = 'Year' + ' ' + str(2019)
print(aa)

bb = 'Year' + ' ' + '2019'
print(bb)

Year 2019
Year 2019


Dictionaries associate keys with value.

In [146]:
x = {'Indonesia': 'Jakarta', 'South Korea': 'Seoul' }
cc = x['Indonesia']
dd = x['South Korea']
print(cc)
print(dd)

Jakarta
Seoul


Iterate over all of the keys.

In [153]:
for country in x:
    print(x[country])

Jakarta
Seoul


Iterate over all of the values.

In [154]:
for capitalcity in x.values():
    print(capitalcity)

Jakarta
Seoul


Iterate over all of the items in the list.

In [155]:
for country, capitalcity in x.items():
    print(country)
    print(capitalcity)

Indonesia
Jakarta
South Korea
Seoul


Unpack a sequence into difference variables.

In [158]:
x = ('Melia', 'Putri', 'Handayani', 'Indonesia')
fname, mname, lname, nationality = x

In [159]:
fname

'Melia'

In [160]:
print(mname)

Putri


In [162]:
lname, nationality

('Handayani', 'Indonesia')

In [167]:
print(lname, ',', fname, mname)

Handayani , Melia Putri


#### More on Strings

Python has a built in method to convenient string formatting. 

In [173]:
sales_record = {
'price': 1000,
'num_items': 2,
'person': 'Melia'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))

Melia bought 2 item(s) at a price of 1000 each for a total of 2000


### Reading and Writing CSV (comma-separated values) Files

Import mpg.csv file which contains fuel economy data for 234 cars.
* mpg: Miles per Gallon
* class: Car Classification
* cty: City mpg
* cyl: Number of Cylinders
* displ: Engine Displacement in Liters
* drv: f=Front-wheel Drive, r=Rear-wheel Drive, 4=4wd
* fl: Fuel (e= Ethanol E85, d= Diesel, r= Regular, p= Premium, c= CNG)
* hwy: Highway mpg
* manufacturer: Car Manufacturer
* model: Car Model
* trans: Type of Transmission
* year: Model Year

In [185]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg=list(csv.DictReader(csvfile))
    
mpg[:1] 

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')])]

csv.DictReader has readin each row of the csv file as a dictionary. 'len' shows the number of dictionaries comprised by the list.

In [186]:
len(mpg)

234

'keys' shows the column names in the csv file.

In [187]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

Find! Average cty (City mpg).

In [191]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

Find! Average hwy (Highway mpg).

In [193]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

Find! The variety of the numbers of cylinders of all cars in the dataset.

In [194]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

Find! The variety of cars brand in the dataset.

In [205]:
manufacturer = set(d['manufacturer'] for d in mpg)
manufacturer

{'audi',
 'chevrolet',
 'dodge',
 'ford',
 'honda',
 'hyundai',
 'jeep',
 'land rover',
 'lincoln',
 'mercury',
 'nissan',
 'pontiac',
 'subaru',
 'toyota',
 'volkswagen'}

Find! The variety of transmission in the dataset.

In [200]:
trans = set(d['trans'] for d in mpg)
trans

{'auto(av)',
 'auto(l3)',
 'auto(l4)',
 'auto(l5)',
 'auto(l6)',
 'auto(s4)',
 'auto(s5)',
 'auto(s6)',
 'manual(m5)',
 'manual(m6)'}

Find! The average of cty for each variety of the numbers of cylinders of all cars in the dataset.

In [203]:
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

Find! The average of cty for each car brand in the dataset.

In [204]:
CtyMpgByManu = []

for m in manufacturer:
    summpg = 0
    manutypecount = 0
    for d in mpg:
        if d['manufacturer'] == m:
            summpg += float(d['cty'])
            manutypecount += 1
    CtyMpgByManu.append((m, summpg / manutypecount))

CtyMpgByManu.sort(key=lambda x: x[0])
CtyMpgByManu

[('audi', 17.61),
 ('chevrolet', 15.00),
 ('dodge', 13.14),
 ('ford', 14.00),
 ('honda', 24.44),
 ('hyundai', 18.64),
 ('jeep', 13.50),
 ('land rover', 11.50),
 ('lincoln', 11.33),
 ('mercury', 13.25),
 ('nissan', 18.08),
 ('pontiac', 17.00),
 ('subaru', 19.29),
 ('toyota', 18.53),
 ('volkswagen', 20.93)]

In [201]:
CtyMpgByTrans = []

for t in trans:
    summpg = 0
    transtypecount = 0
    for d in mpg:
        if d['trans'] == t:
            summpg += float(d['cty'])
            transtypecount += 1
    CtyMpgByTrans.append((t, summpg / transtypecount))

CtyMpgByTrans.sort(key=lambda x: x[0])
CtyMpgByTrans

[('auto(av)', 20.00),
 ('auto(l3)', 21.00),
 ('auto(l4)', 15.94),
 ('auto(l5)', 14.72),
 ('auto(l6)', 13.67),
 ('auto(s4)', 18.67),
 ('auto(s5)', 17.33),
 ('auto(s6)', 17.38),
 ('manual(m5)', 19.26),
 ('manual(m6)', 16.89)]

Find! The (unique value of) classtypes in the dataset.

In [206]:
classification = set(d['class'] for d in mpg) 
classification

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

#### Dates and Times

In [1]:
import datetime as dt
import time as tm

'time' shows the current time in seconds (since Epoch - January 1st, 1970).

In [2]:
tm.time()

1566265649.7529297

Converting the timestamp to datetime.

In [6]:
dtnow = dt.datetime.fromtimestamp(tm.time())
print(dtnow)

2019-08-20 08:48:26.984435


Showing ONLY the year or month or day or hour or minute or second of the current date time.

In [14]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second

(2019, 8, 20, 8, 48, 26)

'timedelta' is a duration expressing the difference between two dates.

In [18]:
delta = dt.timedelta(days = 100)
print(delta)

100 days, 0:00:00


'date.today' shows the current local date.

In [19]:
today = dt.date.today()
print(today)

2019-08-20


In [20]:
dtdelta = today - delta
print(dtdelta)

2019-05-12


In [26]:
today > today - delta

True

#### Objects and map()

An example of a class in Python:

In [28]:
class Person:
    department = 'Department of Systems Management & Engineering'
    
    def set_name(self, new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [31]:
person = Person()
person.set_name('Melia Putri Handayani')
person.set_location('Busan, South Korea')
print('{} lives in {} and studies in the {}'.format(person.name, person.location, person.department))

Melia Putri Handayani lives in Busan, South Korea and studies in the Department of Systems Management & Engineering


Example of mapping the min function between two lists.

In [43]:
store1 = [1.25, 2.00, 3.75, 4.05]
store2 = [2.15, 1.25, 2.25, 5.00]
cheapest = map(min, store1, store2)
cheapest

In [44]:
for item in cheapest:
    print(item)

1.25
1.25
2.25
4.05


#### Lambda and List Comprehensions

Example of lambda that takes in three parameters and adds the first two.

In [56]:
function = lambda a, b, c : 2*a + 3*b - c/3

In [57]:
function(1, 2, 3)

7.0

Iterate from 0 to 99 and show ONLY the even numbers.

In [60]:
numblist = []
for number in range(0, 100):
    if number % 2 == 0:
        numblist.append(number)
print(numblist)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


Show even number with list comprehension.

In [63]:
numblist = [number for number in range(0, 100) if number % 2 == 0]
print(numblist)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


### Numerical Python (NumPy)

In [64]:
import numpy as np

#### Creating Arrays

Create a list and convert it to a numpy array.

In [65]:
numblist = [1, 2, 3]
x = np.array(numblist)
print(x)

[1 2 3]


Or just pass in a list directly.

In [68]:
y = np.array([4, 5, 6])
print(y)

[4 5 6]


Pass in a list of lists to create a multidimensional array.

In [69]:
m = np.array([[7, 8, 9], [10, 11, 12]])
print(m)

[[ 7  8  9]
 [10 11 12]]


Use the shape method to find the dimensions of the array. (rows, columns)

In [70]:
m.shape

(2, 3)

'arange' shows evenly spaced values within a given interval.

In [74]:
n = np.arange(0, 30, 2) #start at 0 up by 2, stop before 30
print(n)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


'reshape' changes the shape of the previous array but containing the same data.

In [80]:
rs53 = n.reshape(5, 3)
print(rs53)

rs35 = n.reshape(3, 5)
print(rs35)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]
 [24 26 28]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


'linspace' shows evenly spaced numbers over a specified interval.

In [114]:
ls = np.linspace(0, 4, 9) #return 9 evenly spaced values from 0 to 4
print(ls)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


'resize' changes the shape and size of array in-place.

In [116]:
ls.resize(3, 3)
print(ls)

[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]


In [105]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

'ones' creates a new array of given shape and type, containing 1.

In [118]:
ones = np.ones((3, 2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


'zeros' creates a new array of given shape and type, containing 0.

In [119]:
zero = np.zeros((3, 3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


'eye' creates a 2-D array with ones on the diagonal and zeros elsewhere.

In [121]:
eye = np.eye(4)
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


'diag' extracts a diagonal or constructs a diagonal array.

In [125]:
z = np.array([7, 8, 9, 10])
np.diag(z)

array([[ 7,  0,  0,  0],
       [ 0,  8,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])

Creating an array using repeating list (or see np.title)

In [147]:
repeat1 = np.array([11, 22, 33] * 3)
print(repeat1)

[11 22 33 11 22 33 11 22 33]


Repeat elements of an array using repeat.

In [146]:
repeat2 = np.repeat([11, 22, 33], 3)
print(repeat2)

[11 11 11 22 22 22 33 33 33]


#### Combining Array

In [149]:
p = np.ones([2, 3], int)
print(p)

[[1 1 1]
 [1 1 1]]


Use 'vstack' to stack arrays in sequence vertically (row wise).

In [151]:
vstack = np.vstack([p, 2*p])
print(vstack)

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]


Use 'hstack' to stack arrays in sequence hrizontally (column wise).

In [153]:
hstack = np.hstack([p, 2*p])
print(hstack)

[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]


#### Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [161]:
j = np.array([10, 20, 30])
k = np.array([5, 10, 15])

In [162]:
print(j+k)

[15 30 45]


In [163]:
print(j-k)

[ 5 10 15]


In [164]:
print(j*k)

[ 50 200 450]


In [165]:
print(j/k)

[2. 2. 2.]


In [168]:
print(k**2)

[ 25 100 225]


#### Dot Product: 

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [170]:
j.dot(k)

700

In [173]:
l = np.array([k, k**2])
print(l)
print(len(l))

[[  5  10  15]
 [ 25 100 225]]
2


Transposing the array l from (2, 3) to (3, 2).

In [176]:
ltransposed = l.T
print(ltransposed)

[[  5  25]
 [ 10 100]
 [ 15 225]]


In [177]:
l.T.shape

(3, 2)

'.astype' to cast to a specific type.

In [178]:
l = l.astype('f')
l.dtype

dtype('float32')

#### Math Function

Numpy has many built in math functions that can be performed on arrays.

In [179]:
ab = np.array([-4, -2, 1, 3, 5])

In [181]:
ab.sum() #calculate -4 + -2 + 1 + 3 + 5

3

In [183]:
ab.max() #find the max value of the list

5

In [184]:
ab.min() #find the min value of the list

-4

In [185]:
ab.mean() #find the average value of the list

0.6

In [186]:
ab.std() #find the standard deviation of the list

3.2619012860600183

'argmax' and 'argmin' shows the index of the max and min values in the array.
Meaning, the index is 0 to 4, index 0 is -4, index 2 is 1, and index 4 is 5.

In [187]:
ab.argmax()

4

In [188]:
ab.argmin()

0

#### Indexing / Slicing

In [190]:
indexing = np.arange(13)**2
print(indexing)

[  0   1   4   9  16  25  36  49  64  81 100 121 144]


Use bracket notation to get the value at a specific index. Indexing start at 0.

In [195]:
indexing[0], indexing[5], indexing[12]

(0, 25, 144)

Use : to indicate a range. array[start:stop]

Leaving start or stop empty will default to the beginning or end of the array.

In [204]:
zeroto = indexing[:10]
print(zeroto)

[ 0  1  4  9 16 25 36 49 64 81]


In [205]:
fromto = indexing[5:10]
print(fromto)

[25 36 49 64 81]


In [207]:
toend = indexing[5:]
print(toend)

[ 25  36  49  64  81 100 121 144]


In [211]:
fromback = indexing[-8:-2]
print(fromback)

[ 25  36  49  64  81 100]


A second : can be used to indicate the step-size. array[start:stop:stepsize]

In [213]:
indexing[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

Multidimensional Array.

In [216]:
rr = np.arange(36)
rr.resize((6, 6))
print(rr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


Use bracket notation to slice: array[row, column]

In [224]:
rr[4, 0] #taking the value in index [4, 0] of the array 

24

In [228]:
rr[3, :] #taking the whole row index 3

array([18, 19, 20, 21, 22, 23])

In [229]:
rr[3, 0:6] #taking the whole row index 3

array([18, 19, 20, 21, 22, 23])

In [232]:
rr[:4, :-1] #taking the whole row index 0 and 3, and excluding the column -1

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [234]:
rr[-1, ::2] #taking the row index -1 and column 1, 3, and 5 only

array([30, 32, 34])

In [237]:
rr[rr > 30] #taking values lower than 30

array([31, 32, 33, 34, 35])

In [245]:
rr[rr > 20] = 0 #change all value greater than 20 as 0
rr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

#### Copying Data

In [249]:
rr2 = rr[:3, :3] #taking only (row, column) index 0, 1, and 2 in  rr
rr2 

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [250]:
rr2[:] = 0 #changing all rr2 array value to 0
rr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [251]:
rr #so, when we re-show the rr array, it has already changed into this

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

To avoid this permanent changes to an array, create a copy of array using 'r.copy' to create a copy that will not affect the original array.

In [259]:
#Example, create another new array
qq1 = np.arange(16)
qq1.resize((4, 4))
print(qq1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [260]:
qq2 = qq1.copy()
qq2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [264]:
qq2[:] = 10
print(qq2, '\n') #copied array
print(qq1) #original array

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### Iterating Over Arrays

Create a new 4 by 3 array of random numbers 0-9.

In [267]:
test = np.random.randint(0, 10, (4, 3))
test

array([[1, 1, 7],
       [8, 6, 6],
       [1, 7, 9],
       [3, 2, 6]])

Iterate by row:

In [268]:
for row in test:
    print(row)

[1 1 7]
[8 6 6]
[1 7 9]
[3 2 6]


Iterate by index:

In [270]:
len(test)

4

In [269]:
for i in range(len(test)):
    print(test[i])

[1 1 7]
[8 6 6]
[1 7 9]
[3 2 6]


In [271]:
for i in range(4):
    print(test[i])

[1 1 7]
[8 6 6]
[1 7 9]
[3 2 6]


Iterate by row and index:

In [272]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [1 1 7]
row 1 is [8 6 6]
row 2 is [1 7 9]
row 3 is [3 2 6]


Use 'zip' to iterate over multiple iterables.

In [274]:
test2 = test**2
print(test2)

[[ 1  1 49]
 [64 36 36]
 [ 1 49 81]
 [ 9  4 36]]


In [275]:
for i, j in zip(test, test2):
    print(i, '+', j, '=', i+j)

[1 1 7] + [ 1  1 49] = [ 2  2 56]
[8 6 6] + [64 36 36] = [72 42 42]
[1 7 9] + [ 1 49 81] = [ 2 56 90]
[3 2 6] + [ 9  4 36] = [12  6 42]
